-- MySQL Script generated by MySQL Workbench
-- 06/24/16 19:39:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payment_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `payment_system` ;

-- -----------------------------------------------------
-- Schema payment_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payment_system` DEFAULT CHARACTER SET utf8 ;
USE `payment_system` ;

-- -----------------------------------------------------
-- Table `payment_system`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_system`.`user_type` ;

CREATE TABLE IF NOT EXISTS `payment_system`.`user_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_system`.`user` ;

CREATE TABLE IF NOT EXISTS `payment_system`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_UserType_idx` (`user_type_id` ASC),
  CONSTRAINT `fk_User_UserType`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `payment_system`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`account_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_system`.`account_type` ;

CREATE TABLE IF NOT EXISTS `payment_system`.`account_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`account_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_system`.`account_status` ;

CREATE TABLE IF NOT EXISTS `payment_system`.`account_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_system`.`account` ;

CREATE TABLE IF NOT EXISTS `payment_system`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(10,2) NOT NULL,
  `account_type_id` INT UNSIGNED NOT NULL,
  `account_status_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Account_AccountType1_idx` (`account_type_id` ASC),
  INDEX `fk_Account_AccountStatus1_idx` (`account_status_id` ASC),
  CONSTRAINT `fk_Account_AccountType1`
    FOREIGN KEY (`account_type_id`)
    REFERENCES `payment_system`.`account_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_AccountStatus1`
    FOREIGN KEY (`account_status_id`)
    REFERENCES `payment_system`.`account_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`bank_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_system`.`bank_card` ;

CREATE TABLE IF NOT EXISTS `payment_system`.`bank_card` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(16) NOT NULL,
  `validity` DATE NOT NULL,
  `password` VARCHAR(4) NOT NULL,
  `cvv` VARCHAR(3) NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BankCard_Account1_idx` (`account_id` ASC),
  INDEX `fk_BankCard_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_BankCard_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `payment_system`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BankCard_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `payment_system`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_system`.`payment` ;

CREATE TABLE IF NOT EXISTS `payment_system`.`payment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NULL,
  `date` DATE NOT NULL,
  `sender_id` INT UNSIGNED NOT NULL,
  `recipient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Payment_User1_idx` (`sender_id` ASC),
  INDEX `fk_Payment_User2_idx` (`recipient_id` ASC),
  CONSTRAINT `fk_Payment_User1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `payment_system`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_User2`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `payment_system`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_system`.`visitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_system`.`visitor` ;

CREATE TABLE IF NOT EXISTS `payment_system`.`visitor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `count` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
